import { Category } from "./category.enum";
import { Subcategory } from "./subcategory.enum";

export const CategoryToSubcategories: Record<Category, Subcategory[]> = {
    [Category.FOOD]: [
      Subcategory.FRUITS,
      Subcategory.VEGETABLES,
      Subcategory.SNACKS,
      Subcategory.CONSERVES,
      Subcategory.BAKERY,
      Subcategory.CANNED_FOOD,
      Subcategory.GRAINS,
      Subcategory.SWEETS,
      Subcategory.OTHERS,
    ],
    [Category.FURNITURE]: [
      Subcategory.TABLES,
      Subcategory.CHAIRS,
      Subcategory.BEDS,
      Subcategory.SOFAS,
      Subcategory.CLOSETS,
      Subcategory.DESKS,
      Subcategory.LAMPS,
      Subcategory.DECORATION,
      Subcategory.BOOKSHELVES,
      Subcategory.RUGS,
      Subcategory.STORAGE,
      Subcategory.OUTDOOR_FURNITURE,
      Subcategory.OTHER_FURNITURE,
    ],
    [Category.WOMEN_CLOTHING]: [
      Subcategory.WOMEN_SHIRTS,
      Subcategory.WOMEN_PANTS,
      Subcategory.WOMEN_JACKETS,
      Subcategory.WOMEN_DRESSES,
      Subcategory.WOMEN_SKIRTS,
      Subcategory.WOMEN_SHORTS,
      Subcategory.WOMEN_SWEATERS,
      Subcategory.WOMEN_SPORTSWEAR,
      Subcategory.WOMEN_COATS,
      Subcategory.WOMEN_SHOES,
      Subcategory.WOMEN_ACCESSORIES,
    ],
    [Category.MEN_CLOTHING]: [
      Subcategory.MEN_SHIRTS,
      Subcategory.MEN_PANTS,
      Subcategory.MEN_JACKETS,
      Subcategory.MEN_SHORTS,
      Subcategory.MEN_SWEATERS,
      Subcategory.MEN_SPORTSWEAR,
      Subcategory.MEN_COATS,
      Subcategory.MEN_SHOES,
      Subcategory.MEN_ACCESSORIES,
    ],
    [Category.ELECTRONICS]: [
      Subcategory.MOBILE_PHONES,
      Subcategory.COMPUTERS,
      Subcategory.TV,
      Subcategory.CAMERAS,
      Subcategory.GAMES_CONSOLES,
      Subcategory.SMARTWATCHES,
      Subcategory.HEADPHONES,
      Subcategory.SPEAKERS,
      Subcategory.HOUSEHOLD_APPLIANCES,
      Subcategory.PRINTERS,
      Subcategory.STORAGE_DEVICES,
      Subcategory.OTHER_ELETRONICS,
    ],
    [Category.BOOKS]: [
      Subcategory.FICTION,
      Subcategory.NON_FICTION,
      Subcategory.TEXTBOOKS,
      Subcategory.CHILDREN_BOOKS,
      Subcategory.BIOGRAPHIES,
      Subcategory.MYSTERY,
      Subcategory.FANTASY,
      Subcategory.SCIENCE_FICTION,
      Subcategory.HISTORY,
      Subcategory.ROMANCE,
      Subcategory.GRAPHIC_NOVELS,
      Subcategory.TRAVEL,
      Subcategory.COOKING,
      Subcategory.OTHER_BOOKS,
    ],
  };
  