export enum Subcategory {
    FRUITS = "Fruits",
    VEGETABLES = "Vegetables",
    SNACKS = "Snacks",
    CONSERVES = "Conserves",
    BAKERY = "Bakery",
    CANNED_FOOD = "Canned Food",
    GRAINS = "Grains",
    SWEETS = "Sweets",
    OTHERS = "Others",
  
    TABLES = "Tables",
    CHAIRS = "Chairs",
    BEDS = "Beds",
    SOFAS = "Sofas",
    CLOSETS = "Closets",
    DESKS = "Desks",
    LAMPS = "Lamps",
    DECORATION = "Decoration",
    BOOKSHELVES = "Bookshelves",
    RUGS = "Rugs",
    STORAGE = "Storage",
    OUTDOOR_FURNITURE = "Outdoor Furniture",
    OTHER_FURNITURE = "Other Furniture",

    WOMEN_SHIRTS = "Women's Shirts",
    WOMEN_PANTS = "Women's Pants",
    WOMEN_JACKETS = "Women's Jackets",
    WOMEN_DRESSES = "Dresses",
    WOMEN_SKIRTS = "Skirts",
    WOMEN_SHORTS = "Women's Shorts",
    WOMEN_SWEATERS = "Women's Sweaters",
    WOMEN_SPORTSWEAR = "Women's Sportswear",
    WOMEN_COATS = "Women's Coats",
    WOMEN_SHOES = "Women's Shoes",
    WOMEN_ACCESSORIES = "Women's Accessories",

    MEN_SHIRTS = "Men's Shirts",
    MEN_PANTS = "Men's Pants",
    MEN_JACKETS = "Men's Jackets",
    MEN_SHORTS = "Men's Shorts",
    MEN_SWEATERS = "Men's Sweaters",
    MEN_SPORTSWEAR = "Men's Sportswear",
    MEN_COATS = "Men's Coats",
    MEN_SHOES = "Men's Shoes",
    MEN_ACCESSORIES = "Men's Accessories",
  
    MOBILE_PHONES = "Mobile Phones",
    COMPUTERS = "Computers",
    TV = "TV",
    CAMERAS = "Cameras",
    GAMES_CONSOLES = "Games and Consoles",
    SMARTWATCHES = "Smartwatches",
    HEADPHONES = "Headphones",
    SPEAKERS = "Speakers",
    HOUSEHOLD_APPLIANCES = "Household Appliances",
    PRINTERS = "Printers",
    STORAGE_DEVICES = "Storage Devices",
    OTHER_ELETRONICS = "Other Electronics",
  
    FICTION = "Fiction",
    NON_FICTION = "Non-Fiction",
    TEXTBOOKS = "Textbooks",
    CHILDREN_BOOKS = "Children's Books",
    BIOGRAPHIES = "Biographies",
    MYSTERY = "Mystery",
    FANTASY = "Fantasy",
    SCIENCE_FICTION = "Science Fiction",
    HISTORY = "History",
    ROMANCE = "Romance",
    GRAPHIC_NOVELS = "Graphic Novels",
    TRAVEL = "Travel",
    COOKING = "Cooking",
    OTHER_BOOKS = "Other Books",
  }
  